### ISSUE TITLE
Available Testing?

### ISSUE THREAD

**Issue by bagelbytes61** [osrf/rmw_zenoh#145]
Hello.

Is there any comprehensive testing available to run against the Zenoh RMW beyond the talker/listener example described in the README? We are eager to assist in debugging #143 and also help uncover any additional bugs present on Ubuntu 24.04, and it would be extremely valuable for us to be able to run the tests ourselves in order to facilitate that. If they do exist would it be possible for you to point us in the right direction and potentially give a brief explanation of how to run the tests?

Thank you.

**Comment by Yadunund** [comment]
There's nothing preventing one from running any existing ROS 2 application (eg. Nav2, moveit, Open-RMF, etc) with rmw_zenoh instead of the default middleware option. So you're not limited to just talker/listener.

There are the official ROS 2 [system_tests](https://github.com/ros2/system_tests) which you could try although some modifications may be needed to the test cases.

Please be mindful that the rmw_zenoh is still under active development (not yet ready for widespread testing) and the core team is spread pretty thin between development here and the Jazzy release. So we may not be able to guide you as expected but would greatly appreciate your efforts with testing and fixing any bugs encountered.

**Comment by Yadunund** [comment]
I've run `rmw_zenoh` through all the system tests and opened bug tickets with issues that surfaced. If you're still able to help, please take a look at those tickets.
