### ISSUE TITLE
Clock topic in bag negative

### ISSUE THREAD

**Issue by thomasemter** [osrf/rmw_zenoh#337]
Hi,

we are running some test with rmw_zenoh and the results are very promising. Somehow peculiar is the `/clock` when playing back a bag file with `--clock` since it shows negative timestamps.

# Steps to reproduce
## Record bag file:

```bash
# terminal 1
ros2 run rmw_zenoh_cpp rmw_zenohd
```

```bash
# terminal 2
export RMW_IMPLEMENTATION=rmw_zenoh_cpp
ros2 run demo_nodes_cpp talker
```

```bash
# terminal 3
export RMW_IMPLEMENTATION=rmw_zenoh_cpp
ros2 bag record -a
```

## Play back and echo clock:

```bash
# terminal 3
ros2 bag play rosbag2_... --clock
```

```bash
# terminal 2
ros2 topic echo /clock
```

## Result:

```bash
# terminal 2
clock:
  sec: -1142771387
  nanosec: 756485177
---
clock:
  sec: -1142771387
  nanosec: 781476412
---
clock:
  sec: -1142771387
  nanosec: 806413161
---
clock:
  sec: -1142771387
  nanosec: 831491893
---
clock:
  sec: -1142771387
  nanosec: 856471721
```

**Comment by clalancette** [comment]
Can you please explain how you are getting the `/clock` topic?  That is not published when you just run `ros2 run demo_nodes_cpp talker`.

**Comment by christophebedard** [comment]
`ros2 bag play` can publish to `/clock` depending on how it is configured, e.g., `--clock`. The full `ros2 bag play` command is definitely not clear in the issue, though.

**Comment by thomasemter** [comment]
Oh, I am so sorry. The `--clock` got lost in copying. It should indeed be
```
# terminal 3
ros2 bag play rosbag2_... --clock
```
I fixed the original post, too.

**Comment by clalancette** [comment]
OK, thanks.  Now I can reproduce.

So I see what the problem is.  The problem is that during the reception of a message, we are using the timestamp that is coming from Zenoh for the delivery time.  But that time is actually an NTP64 time, not a number of nanoseconds since the epoch.  Since the rest of our system depends on nanoseconds since the epoch, we have a mis-match.

Tomorrow I'll work on a fix to convert between them.  Thanks for bringing this up, it is an important problem.

**Comment by thomasemter** [comment]
Thank you for looking into it.

**Comment by thomasemter** [comment]
Thank you very much :-)
